config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'rooms#index'
  resources :rooms, only:[:index, :show]
  resources :messages, only:[:create]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate

  private

  def authenticate
    redirect_to login_url unless current_user
  end

  def current_room
    @room ||= Room.find(session[:current_room]) if session[:current_room]
  end
  
  def current_user
    @user ||= User.find(session[:current_user]) if session[:current_user]
  end

  helper_method :current_user, :current_room
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    message = Message.new(message_params).save
    redirect_back fallback_location: root_path
  end

  def message_params
    params.require(:message).permit(:content).merge(user_id: current_user.id, room_id: current_room.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :rooms

  def index
   
  end

  def show
    set_current_room
    @messages = room.messages
  end

  private

  def set_current_room
    session[:current_room] = params[:id] if params[:id]
  end

  def rooms
    @rooms ||= Room.all
  end

  def room 
    @room ||= Room.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :authenticate, except: [:new, :create]

  def new
  end

  def create
    if user.try(:authenticate, params[:password])
      session[:current_user] = user.id
      redirect_to root_url
    else
      redirect_to login_url
    end
  end

  def destroy
    session[:current_user] = nil
    redirect_to login_url
  end

  private

  def user
    @user = User.find_by_email(params[:email])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatroom</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/index.html.erb
<div id="container">

  <%= render "shared/nav" %>
       
</div>

app/views/rooms/show.html.erb
<div class="container">
  <%= render "shared/nav" %>
  <div id="chat-container">
      <header><%= current_room.name %> </header>
      <div id="chat-box">
        <% @messages.each do |msg|%>
          <div class="row">
            <p><%= msg.content %></p>
            <span>--<%= msg.user.name %></span>
          </div>
        <% end %>
      </div>
      <div id="form-box">
        <%= form_for :message, url: messages_path do |f| %>
          <%= f.text_field :content , id: 'message_input' %>
          <%= f.submit 'Send Message' %>
        <% end %>
      </div>
    </div>   
</div>

app/views/shared/_nav.html.erb
<nav>
    <ul class="pull-left">
      <% @rooms.each do |room| %>
        <li><%= link_to room.name, room_path(room) %></li>
      <% end %>
    </ul>
    <ul class="pull-right">
      <li><%= link_to 'Logout', logout_path %></li>
    </ul>
  </nav>